const brownTags = {
    ABL: "pre-qualifier",
    ABN: "pre-quantifier",
    ABX: "pre-quantifier",
    AP: "post-determiner",
    AT: "article",
    BE: "*be*",
    BED: "*were*",
    BEDZ: "*was*",
    BEG: "*being*",
    BEM: "*am*",
    BEN: "*been*",
    BER: "*are, art*",
    BEZ: "*is*",
    CC: "coordinating conjunction",
    CD: "cardinal numeral",
    CS: "subordinating conjunction",
    DO: "*do*",
    DOD: "*did*",
    DOZ: "*does*",
    DT: "single determiner",
    DTI: "singular or plural determiner/quantifier",
    DTS: "plural determiner",
    DTX: "determiner/double conjunction",
    EX: "existential *there*",
    FW: "foreign word",
    HL: "word occurring in headline",
    HV: "*have*",
    HVD: "*had* (past tense)",
    HVG: "*having*",
    HVN: "*had* (past participle)",
    HVZ: "*has*",
    IN: "preposition",
    JJ: "adjective",
    JJR: "comparative adjective",
    JJS: "semantically superlative adjective",
    JJT: "morphologically superlative adjective",
    MD: "modal auxiliary",
    NC: "cited word",
    NN: "singular or mass noun",
    NN$: "possessive singular noun",
    NNS: "plural noun",
    NNS$: "possessive plural noun",
    NP: "proper noun or part of name phrase",
    NP$: "possessive proper noun",
    NPS: "plural proper noun",
    NPS$: "possessive plural proper noun",
    NR: "adverbial noun",
    NRS: "plural adverbial noun",
    OD: "ordinal numeral",
    PN: "nominal pronoun",
    PN$: "possessive nominal pronoun",
    PP$: "possessive personal pronoun",
    PP$$: "second (nominal) possessive pronoun",
    PPL: "singular reflexive/intensive personal pronoun",
    PPLS: "plural reflexive/intensive personal pronoun",
    PPO: "objective personal pronoun",
    PPS: "3rd singular nominative pronoun",
    PPSS: "other nominative personal pronoun",
    QL: "qualifier",
    QLP: "post-qualifier",
    RB: "adverb",
    RBR: "comparative adverb",
    RBT: "superlative adverb",
    RN: "nominal adverb",
    RP: "adverb/particle",
    TL: "word occurring in title",
    TO: "infinitive marker *to*",
    UH: "interjection, exclamation",
    VB: "verb, base form",
    VBD: "verb, past tense",
    VBG: "verb, present participle/gerund",
    VBN: "verb, past participle",
    VBZ: "verb, 3rd singular present",
    WDT: "*wh-* determiner",
    WP$: "possessive *wh-* pronoun",
    WPO: "objective *wh-* pronoun",
    WPS: "nominative *wh-* pronoun",
    WQL: "*wh-* qualifier",
    WRB: "*wh-* adverb"
}

export default brownTags